/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.hajofa.ui;


import ca.hajofa.entites.*;
import ca.hajofa.services.jpa.*;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fatim
 */
public class FenInscription extends javax.swing.JFrame {

    //objet type buttongroup
    ButtonGroup group = new ButtonGroup();

    //genere la liste prof
    List<Enseignants> listeProfs = EnseignantsServices.GetAllProfs();

    //generer la liste etudiants
    List<Etudiants> listeEtudiants = EtudiantsServices.GetAllEtudiants();

    /**
     * Creates new form FenEnregistrer
     */
    public FenInscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMdp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnEnregistrer = new javax.swing.JButton();
        txtMdp2 = new javax.swing.JPasswordField();
        txtMdp1 = new javax.swing.JPasswordField();
        banner = new javax.swing.JLabel();
        rBtnEtudiant = new javax.swing.JRadioButton();
        rBtnEnseignant = new javax.swing.JRadioButton();
        lblRetour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMdp.setBackground(new java.awt.Color(37, 83, 158));

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Première utilisation");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom");

        txtNom.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prénom");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirmer mot de passe");

        txtPrenom.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Courrier électronique");

        txtEmail.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mot de passe");

        btnEnregistrer.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        txtMdp2.setEnabled(false);

        txtMdp1.setEnabled(false);

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ideas.gif"))); // NOI18N

        rBtnEtudiant.setText("Étudiant");
        rBtnEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnEtudiantActionPerformed(evt);
            }
        });

        rBtnEnseignant.setText("Enseignant");
        rBtnEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnEnseignantActionPerformed(evt);
            }
        });

        lblRetour.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        lblRetour.setForeground(new java.awt.Color(255, 255, 255));
        lblRetour.setText("Retour");
        lblRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout txtMdpLayout = new javax.swing.GroupLayout(txtMdp);
        txtMdp.setLayout(txtMdpLayout);
        txtMdpLayout.setHorizontalGroup(
            txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMdpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtMdpLayout.createSequentialGroup()
                        .addGroup(txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtMdpLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMdp2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(txtMdpLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(txtMdpLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMdpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMdpLayout.createSequentialGroup()
                                .addComponent(rBtnEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rBtnEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMdpLayout.createSequentialGroup()
                                .addComponent(lblRetour)
                                .addContainerGap())))))
        );
        txtMdpLayout.setVerticalGroup(
            txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtMdpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(txtMdpLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rBtnEnseignant)
                            .addComponent(rBtnEtudiant))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMdp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(txtMdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtMdpLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMdpLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRetour))))
                    .addComponent(banner))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        //attribut
        String courriel = txtEmail.getText();  
        //verification des champs
        if (verifierChampsInscription()) {   
            if (rBtnEtudiant.isSelected()) {
                //creer objet etudiant 
                Etudiants etudiant = new Etudiants (txtNom.getText(),txtPrenom.getText(),txtEmail.getText(),txtMdp2.getText()); 
                if(EtudiantsServices.createEtudiant(etudiant)){
                   JOptionPane.showMessageDialog(null, "Étudiant a été crée!",
                        "Valide", JOptionPane.INFORMATION_MESSAGE);
                   //retour a la page de connexion
                   deconnexion();
                }   
            } else if (rBtnEnseignant.isSelected()) {
                //creer objet etudiant 
                Enseignants prof = new Enseignants (txtNom.getText(),txtPrenom.getText(),txtEmail.getText(),txtMdp2.getText());
                if(EnseignantsServices.createEnseignant(prof)){
                   JOptionPane.showMessageDialog(null, "Enseignant a été crée!",
                        "Valide", JOptionPane.INFORMATION_MESSAGE);
                   //retour a la page de connexion
                   deconnexion();
                }
            }
        }
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void lblRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetourMouseClicked
        deconnexion();
    }//GEN-LAST:event_lblRetourMouseClicked

    private void rBtnEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnEtudiantActionPerformed

        //stock valeur de  radio button dans mon objet group
        group.add(rBtnEtudiant);

        if (rBtnEtudiant.isSelected()) {
            txtNom.setEnabled(true);
            txtPrenom.setEnabled(true);
            txtEmail.setEnabled(true);
            txtMdp1.setEnabled(true);
            txtMdp2.setEnabled(true);
        }

    }//GEN-LAST:event_rBtnEtudiantActionPerformed

    private void rBtnEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnEnseignantActionPerformed
        //stock valeur de  radio button dans mon objet group
        group.add(rBtnEnseignant);

        if (rBtnEnseignant.isSelected()) {
            txtNom.setEnabled(true);
            txtPrenom.setEnabled(true);
            txtEmail.setEnabled(true);
            txtMdp1.setEnabled(true);
            txtMdp2.setEnabled(true);
        }
    }//GEN-LAST:event_rBtnEnseignantActionPerformed



    private boolean verifierChampsInscription() {
        //attribut
        boolean flag = true;
        final String emailRegex = "^(.+)@(.+)$";
        //verification des champs
        if (txtNom.getText().isEmpty() || txtPrenom.getText().isEmpty() || txtEmail.getText().isEmpty()
                || txtMdp1.getText().equals("") || txtMdp2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs!",
                    "Invalide", JOptionPane.ERROR_MESSAGE);
            flag = false;
        } else if (!(txtMdp1.getText().equals(txtMdp2.getText()))) {
            JOptionPane.showMessageDialog(null, "Les mots de passes ne sont pas pareils!",
                    "Invalide", JOptionPane.ERROR_MESSAGE);
            flag = false;
        }else if((!(txtEmail.getText().matches("^(.+)@(.+)$"))) || (!(txtEmail.getText().contains(".")))){
            JOptionPane.showMessageDialog(null, "Entrez un courrier valide!",
                    "Invalide", JOptionPane.ERROR_MESSAGE);
            flag=false;
        }
        return flag;
    }
    
    /**
     *La methode deconnexion permet de nous redirect a la fenetre Connexion
     * 
     * @return
     */
    private void deconnexion() {
        FenConnexion fenCnx = new FenConnexion();
        fenCnx.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenCnx.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JRadioButton rBtnEnseignant;
    private javax.swing.JRadioButton rBtnEtudiant;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPanel txtMdp;
    private javax.swing.JPasswordField txtMdp1;
    private javax.swing.JPasswordField txtMdp2;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
